analyze_user_profile:
  description: >
    Analyze the simplified user profile focusing on their current piano level, sheet music reading ability,
    practice frequency, and time commitment. Create a comprehensive individual learning profile with
    recommendations tailored to their specific situation.
  expected_output: >
    Provide a detailed analysis of the user's piano learning profile including:
    - Current skill level assessment (beginner, intermediate, advanced)
    - Sheet music reading proficiency and areas for improvement
    - Practice schedule analysis based on frequency and time commitment
    - Realistic learning pace and goals given their available practice time
    - Recommended focus areas based on their current level
    - Suggested repertoire appropriate for their skill level
    - Any additional insights that would help personalize their learning journey
  agent: learning_plan_agent

create_learning_plan:
  description: >
    Based on the user profile analysis, create a structured 3-month piano learning plan. 
    Design weekly lessons that are achievable within the user's practice frequency and time commitment.
    Each week should include a specific focus topic and an appropriate piece to practice.
    Make sure to check with a human which week they want to practice now.
  expected_output: >
    First Month: Building Foundation
      Week 1: Topic with specific technique focus
      Week 2: Topic with clear learning objectives
      Week 3: Topic with progressive skill development
      Week 4: Topic with practical application
    Second Month: Skill Development
      Week 5: Topic building on first month's progress
      Week 6: Topic introducing new concepts
      Week 7: Topic reinforcing previous learning
      Week 8: Topic with performance preparation
    Third Month: Musical Expression
      Week 9: Topic focusing on interpretation
      Week 10: Topic enhancing technical skills
      Week 11: Topic integrating all learned concepts
      Week 12: Topic with performance goals
  agent: learning_plan_agent


explain_music_theory:
  description: >
    Create a detailed explanation of the current week's topic that is accessible and engaging.
    Include practical examples, interactive exercises, and clear connections to piano playing.
    Ensure explanations are appropriate for the user's current level and reading ability.
  expected_output: >
    Week X: Topic Title
      - Clear explanation of the concept with beginner-friendly terminology
      - Practical examples showing real-world application
      - Step-by-step interactive exercises tailored to skill level
      - Suggested practice techniques within time constraints
      - Additional resources for further exploration
  agent: music_theory_agent

create_quiz:
  description: >
    Generate a quiz based on the music theory covered in the current week's lesson.
    Questions should reinforce key concepts and be appropriate for the user's level.
    Include helpful feedback for each answer to enhance learning.
  expected_output: >
    {"topic":"Week X: Topic Title", 
     "questions": ["Question focusing on key concept", "Question applying theory to practice", "Question testing understanding"],
     "Answer": {"Q1": "Helpful explanation reinforcing learning", "Q2": "Constructive feedback with practical tip", "Q3": "Encouraging response with additional insight"}}
  agent: music_quiz_agent